name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
    inputs:
      number1:
        description: "Enter first number"
        required: true
        type: number
      number2:
        description: "Enter second number"
        required: true
        type: number

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Add Two Numbers
        run: |
          num1=${{ github.event.inputs.number1 }}
          num2=${{ github.event.inputs.number2 }}
          sum=$((num1 + num2))

          echo "First Number : $num1"
          echo "Second Number: $num2"
          echo "Sum          : $sum"
      

